### ISSUE TITLE
Consider indirect sibling css selector in toggle

### ISSUE THREAD

**Issue by julczka** [umbraco/Umbraco.UI#152]
When extending the uui-toggle component, when you override the `renderCheckbox()` method, to keep the component working you cannot really add any sibling to `#slider` without breaking the component, as the `#slider` is no longer an adjacent sibling of `input`.

https://github.com/umbraco/Umbraco.UI/blob/89e0441bfb4ada1763e55a2351888e3feb4f9040/packages/uui-toggle/lib/uui-toggle.element.ts#L131

Would you consider changing the adjacent sibling `+` combinator to a general sibling `~` instead in any selector that targets slider and input?

**Comment by iOvergaard** [comment]
That's a really good idea, @julczka. Would you consider making a PR for it?
