### ISSUE TITLE
Assumptive base styles

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco.UI#164]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

Latest

### Bug summary

Whilst reviewing a demo @warrenbuckley created https://codepen.io/warrenbuckley/pen/WNdxOLv I noticed his "Praise" panel on the right hand side was formatted badly with the header overlapping. When reviewing why this is, it appears this comes from the UUI css file which is applying negative left margins to all `hX` tags. This to me feels like a style that is situation specific and should not be a base style for the h tags as clearly these can be used in places that style doesn't make sense.

### Steps to reproduce

Review @warrenbuckley's demo link to see it reproduced

### Expected result / actual result

I don't think global styles for elements should have this kind of formatting. It feels like it's assuming that the h tags will be used in a specific location / within a specific element and in that particular use case negative margins make sense. But from a global / reuse perspective, these styles should not apply.

**Comment by nielslyngsoe** [comment]
I can confirm the issue exists. The main problem here is that we append styling to the slotted element, we should not be styling slotted elements, instead, we should have the border applied to the slot element.

We would also like to re-consider how we do optical adjustments of typography, as I understand the chosen method might be intrusive to developers.

The reasoning for the negative margin is to visually ensure text is aligned correctly. An example of this is that the left side of the first character in a line should follow the left side of the first character on other lines.
Here is an example from a story displaying how the negative margin(-5px on the H1) has ensured that the typography is aligned correctly:
![image](https://user-images.githubusercontent.com/6791648/159667876-bc0d0351-14d0-4199-bc26-2e3902c45aa5.png)

It is from a visual point that we want to ensure headlines are corrected horizontally to ensure the vertical alignment across elements.
Therefore it's an interest to apply this negative margin to all hX-tags within the uui-text class selector.

**Comment by mattbrailsford** [comment]
@nielslyngsoe I wonder if you could take a concept from tailwind and when you want to render typography in this kind of way, it is done sow in a special `prose` container https://tailwindcss.com/docs/typography-plugin

This way it is explicit that the markup should be considered a typographic block, where as if it's used elsewhere outside of such a block, it doesn't apply those corrections.

**Comment by nielslyngsoe** [comment]
@mattbrailsford Thanks for sharing, actually that's exactly the approach we have taken but I´m not sure if Warren's example is using it too broadly.

The concept is that we expose two CSS-classes `uui-font` and `uui-text`. 

uui-font provides the typography and nothing else.

uui-text sets specifics for p, h1, h2, h3..., quote etc. to achieve the right setup for an article, just like the `prose` class of your example.

If any ideas of your comes to mind on how we can help clarifying that concept, then please let me know :-)
