### ISSUE TITLE
uui-input append slot does not work well with button 

### ISSUE THREAD

**Issue by julczka** [umbraco/Umbraco.UI#227]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

0.2.1

### Bug summary

When `uui-button` is put to the `uui-input` append (and prepend too I suppose) slot it does not work nicely out of the box. The button is too tall. 

### Specifics

![image](https://user-images.githubusercontent.com/56249914/172328767-d81149b9-1c22-48d9-be14-61c6041acc7d.png)

### Steps to reproduce

Put `uui-button` with icon into the `uui-input` `append` slot

### Expected result / actual result

Although it is of course possible to tackle that with a bit of styling, It woulod be nice if that worked correctly out of the box. I think it quite often might be a desired combination to have a button in the input slot and add some funcionality to it. It would also make a nice story in the storybook.

**Comment by nielslyngsoe** [comment]
Fixed https://github.com/umbraco/Umbraco.UI/pull/236https://github.com/umbraco/Umbraco.UI/pull/236
