### ISSUE TITLE
Storybook: not all custom properties are listed in the custom properties story. 

### ISSUE THREAD

**Issue by julczka** [umbraco/Umbraco.UI#240]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

1.0.0-RC

### Bug summary

The `--uui-color-interactive` and `--uui-color-default` custom properties are not listed [in this story ](https://uui.umbraco.com/?path=/story/design-custom-properties--interface-colors)

All available custom properties should be there along with some short instrucion what "standalone" and "emphasis" means. It is not clear (at least for me) what are the use cases for those (which should be used for hover state for example). A few simple examples might be nice. 

### Steps to reproduce

not applicable

**Comment by iOvergaard** [comment]
Hi @julczka 

Thanks! We should get on that.

One thing to note: The storybook available at uui.umbraco.com is running the latest stables release (0.2.2) and not the RC. You can find the RC on [Chromatic](https://62189360eeb21b003ab2f4ad-xqzuzdqpas.chromatic.com/) if need be.

But those particular variables are missing in both places, so thanks for that :)
