### ISSUE TITLE
Swatches with labels are not shown in the best way

### ISSUE THREAD

**Issue by loivsen** [umbraco/Umbraco.UI#423]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

1.0.0, branch color-picker

### Bug summary

When we show label for `<uui-swatches>` and `<uui-swatch>`, they may take up odd space, especially if the labels for all swatches are not the same length. See picture
![image](https://user-images.githubusercontent.com/108085781/219699271-04164efb-1a51-4ab9-85bf-f46ce3b7a5e7.png)

There really isnt much room for the labels, but they look wonderful in other places like eye-dropper, icon-picker, etc. where labels arent needed.

A suggestion would be that they change form/size if the labels are being shown. In the old backoffice it looked like this with plenty of space for the color, the label, and the color code
![image](https://user-images.githubusercontent.com/108085781/219701062-d56bc9f7-803d-4075-a53e-e425f35efd5b.png)

May also consider how the swatch should handle super long labels. (like the uui-table handles overflow, see https://uui.umbraco.com/?path=/story/uui-table--overflow-detection)

### Steps to reproduce

Set the show labels to true.
`<uui-color-swatch value="#FF0000" label="I am a beautiful color" showLabel="true"></uui-color-swatch>`

**Comment by iOvergaard** [comment]
Will be released with 1.2.0.
