### ISSUE TITLE
UUI-INPUT doesn't display *spaces* if used inside UUI-TABLE

### ISSUE THREAD

**Issue by jesp209i** [umbraco/Umbraco.UI#437]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

uui-input 1.10 and uui-table 1.1.0

### Bug summary

Placing a <uui-input> inside a <uui-table-cell> causes spaces in the input field to be ignored.
expected input sould look like: "Hello this is input" but the result is: "Hellothisisinput"

### Steps to reproduce

```html
<uui-input></uui-input> no trouble, all good :)
<uui-table>
....
  <uui-table-cell>
    <uui-input></uui-input>  no spaces when inputting :(
  </uui-table-cell>
</uui-table>
```

**Comment by iOvergaard** [comment]
Hi @jesp209i, thanks for reporting this and @lauraneto for figuring out where the problem originates. Much appreciated H5YR!

A fix to this problem is currently being reviewed and we aim to release it with 1.3.0, which will be out as a Release Candidate shortly.
