### ISSUE TITLE
Button text color hover not taking effect

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco.UI#443]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

Default with Umbraco 10.4.1

### Bug summary

When specifying --uui-button-contrast-hover on buttons, the color set does not take eefect on hover.

### Steps to reproduce

Create a uui-button as `<uui-button type="button" look="secondary" color="default" style="--uui-button-background-color-hover: var(--uui-palette-violet-blue-dark);--uui-button-contrast-hover:#ffffff"></uui-button>`

You'll notice that the background takes effect but not the text.

**Comment by iOvergaard** [comment]
The fix has been merged and it will be released in 1.4.0. Thanks so much for reporting this!
