### ISSUE TITLE
Advanced Table Usage

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco.UI#46]
It would be good to see example of more advanced use cases in the Table control

1. Column ordering
2. Column scrolling (an alternative to overflowing content, could we allow the table to scroll horizontally?)
3. Multi-line content
4. None text content (images, other controls)

Maybe take a look at https://gridjs.io/ and https://www.datatables.net/ for inspiration.

**Comment by mattbrailsford** [comment]
Here's a couple of examples of tables from Vendr that I'd love to be able to achive using these new controls (currently using custom ones)

![image](https://user-images.githubusercontent.com/527305/140292237-f299aa2e-7bf7-4e39-929f-bd8eda688dea.png)

![image](https://user-images.githubusercontent.com/527305/140292315-272008bd-b596-4e9b-b03b-dc3155c77fc8.png)

**Comment by nielslyngsoe** [comment]
Thanks @mattbrailsford for giving us this focus on these types of details. I will make sure get to cover this in near future.

**Comment by bjarnef** [comment]
It is worth mentioning Vendr Reviews as well, which shows icons in the row cell as well. It would be great to ensure custom icons can be used here as well.

![image](https://user-images.githubusercontent.com/2919859/147738975-8a9ec6b0-9b71-4d52-ac9f-a0b26af39c7d.png)

**Comment by madsrasmussen** [comment]
Thanks for sharing @bjarnef  👍 

FYI: We have a draft PR where we play around the some "advanced" table features if you would like to follow along. Today the table is very flexible, but you also have to implement all advanced features yourself (sorting, selection, etc.). We will have to find the right balance between providing the same experience for everyone and still allowing flexibility.

You can find the work in progress here #84

**Comment by bjarnef** [comment]
@madsrasmussen Yeah, I noticed you are working on that and I had a glance at the code. It seems in hover and when a row is selected all icons are hidden though?
https://github.com/umbraco/Umbraco.UI/blob/3e3df79902810f05552169e1c9ba1f92f3d086cd/packages/uui-table/lib/uui-table-with-selection-example.ts#L36-L39

Maybe the icon/checkbox thing could be a component itself?

**Comment by nielslyngsoe** [comment]
@bjarnef you are right. I would say this becomes implementation specific. We should have selected uui-icon by another specific selector, but as this is just an example it's okay. But if you like a PR is of course welcome.

I'll close this issue for now as we have the example available now :-)
