### ISSUE TITLE
Single Color Swatch not Rendering

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco.UI#469]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

OOB in Umbraco 10.5.1

### Bug summary

Single Color Swatch as per the [docs here](https://uui.umbraco.com/?path=/docs/uui-color-swatch--overview) is not rendering.

### Steps to reproduce

Just add the exact markup from the example `<uui-color-swatch label="#d0021b"></uui-color-swatch>`

**Comment by julczka** [comment]
Hi! Could you specify bit more? Good way to debug that is to inspect the element in dev tools and see if there is a shadowRoot inside. If it's just a tag and you cannot unfold it in chrome dev tools that usually means that the element was not registered correctly.

**Comment by TRexStark** [comment]
Hi @julczka

I have checked the dev tools - hence I raised this.

To verify whether the element registration is from my end or not, I added a button with a swatch in the same view. The button is rendering as intended but the swatch is not.

Please see screenshot below.

<img width="760" alt="Screenshot 2023-05-01 at 2 38 13 pm" src="https://user-images.githubusercontent.com/70106895/235407740-6c0a4c71-5415-4be6-8761-d96e8674343d.png">

**Comment by julczka** [comment]
Hi, thanks for clarifying. v10 of umbraco has an [older version of UI Library](https://github.com/umbraco/Umbraco-CMS/blob/6afa6d2fe3891d55a675c63d3c02a0ee074fab3c/src/Umbraco.Web.UI.Client/package.json#L21) and that does not include color picker and that is the reason it is not rendering. You can add color picker as an individual dependency if You want to use it in this version.

**Comment by iOvergaard** [comment]
Hello @TRexStark 

Thanks for the report. The issue is as mentioned by Julia due to 10.5.1 not running the latest version of the UI library. There will always be a delay between supported versions of Umbraco CMS and the release of the UI library being in sync.

The new components will be available with the release of Umbraco 10.6 which is using the latest version of the UI library.

Reference https://github.com/umbraco/Umbraco-CMS/pull/14186

**Comment by TRexStark** [comment]
Thanks @iOvergaard  for the info ... I wasn't sure how to respond or how to take this from there as no solution was provided initially.
