### ISSUE TITLE
Typo in the storyboard docs for input

### ISSUE THREAD

**Issue by nickh364** [umbraco/Umbraco.UI#48]
A small thing but the code is "`<uui-input><uui-input/>`" instead of "`<uui-input></uui-input>`"

https://uui.umbraco.com/?path=/docs/uui-input--aaa-overview

**Comment by JesmoDev** [comment]
I'm not sure i understand the issue. Can you elaborate?

**Comment by nickh364** [comment]
> I'm not sure i understand the issue. Can you elaborate?

I guess it removed what I put in quotes. <uui-input><uui-input/> should be <uui-input></uui-input>

**Comment by JesmoDev** [comment]
Thanks! This has now been fixed.
