### ISSUE TITLE
UUI Table: Do not render "..." if cell has overflow but no text node

### ISSUE THREAD

**Issue by julczka** [umbraco/Umbraco.UI#51]
If the table cell has overflow but has no text node as a child, change the `text-overflow CSS property from `ellipsis to something else, so the ... does not show up. See screenshot.

![image](https://user-images.githubusercontent.com/56249914/141104435-0ab36dab-777d-4860-aba3-83780ff03481.png)

**Comment by iOvergaard** [comment]
Hi,

This should be fixed now. You should define the property `clip-text` on cells that should be clipped with ellipsis like so:

```html
<uui-table-cell clip-text>Cell 1</uui-table-cell>
```
