### ISSUE TITLE
[BUG] uui-color-area: Sometimes resets coordinates when selecting a color

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco.UI#533]
[...] in inline color picker, it seems the handle is flickering while dragging, and dragging to bottom, the handle shortly jump to bottom left corner, which doesn't happen in the color area itself.

But it seems also to happen on [uui.umbraco.com](https://uui.umbraco.com/) so probably another issue somewhere.

_Originally posted by @bjarnef in https://github.com/umbraco/Umbraco.UI/issues/532#issuecomment-1638134383_

**Comment by bjarnef** [comment]
The issue isn't specific in inline mode, but seems to happen in color picker. It may be a rounding issue.

**Comment by iOvergaard** [comment]
> The issue isn't specific in inline mode, but seems to happen in color picker. It may be a rounding issue.

Ok, I updated the title. The more we know the better. Anyway, I have marked this as up-for-grabs if you or anyone else would like to take a look at it, or maybe even just figure out a surefire way to reproduce it.

**Comment by bjarnef** [comment]
@iOvergaard it seems to be same issue when pointer events in color picker.

In color area it works smooth, in color picker dragging the handle is flickering a bit and dragging to bottom (black), the handle shortly jump to bottom left.

https://github.com/umbraco/Umbraco.UI/assets/2919859/fff543b2-5e16-430b-8144-30c2c151a146

**Comment by iOvergaard** [comment]
@bjarnef probably due to the d.ts caching in Typescript, because we build incrementally. If you run `npm run clean` first that might fix things, otherwise go into packages/uui-base/lib and delete the .d.ts files in there and it should work (if the export exists in the source file).

**Comment by bjarnef** [comment]
When dragging around in color picker, the `gridHandleX` sometimes return zero and thus jump to left, although it shouldn't

![image](https://github.com/umbraco/Umbraco.UI/assets/2919859/0c05f294-8668-4eb9-af63-8f82e2336e92)

It seems something may override/reset the current saturation while while dragging the handle.

**Comment by bjarnef** [comment]
@iOvergaard the `gridHandleX` is changed in `value` set, at `parsed.toHsl()`, where `s` returns 0.
It seems to be something similar with hue value.

https://github.com/umbraco/Umbraco.UI/pull/536
