### ISSUE TITLE
Range Slider interaction fields intercept unexpected

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco.UI#562]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

1.4.0-rc.1

### Bug summary

When dragging with the mouse on the slider, there is an unexpected interaction with the whole range when having the mouse close to the minimum or maximum pin.

The moving the mouse for a movement of the minimum or maximum pin, it sometimes happens that I get to move the whole bar.

https://github.com/umbraco/Umbraco.UI/assets/6791648/8bbd5a35-4d48-4850-8b23-8141b91ca9f8

I would expect to only be able to grab the minimum value pin, when close to the min pin.
Same for the maximum.
I would not expect to be able to interact with the full range unless I move my mouse in between the two pins.

The area of interaction on the pins should count for the radius of the outer blue circle. Approximately an interaction field with an 18 pixels diameter. So when moving the mouse vertically, like in the video above, I should not be able to grab the full range.

I would also love a visual indication when hovering a single pin. Similar style when hovering over the range. But only the dot and the circle around it should be highlighted with a brighter blue color.

### Steps to reproduce

Move the mouse vertically, to experience that a few pixels interact with the range instead of the pin.
See the video posted above.

**Comment by AyushK-101** [comment]
@nielslyngsoe I would like to work on this

**Comment by nielslyngsoe** [comment]
@AyushK-101 cool 👍, go ahead :-)
