### ISSUE TITLE
Adding icon that uses stroke instead of fill makes icon display incorrectly

### ISSUE THREAD

**Issue by UnicornSez** [umbraco/Umbraco.UI#586]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

1.4.0

### Bug summary

In the uui icon element the `:host sv` has fill property set to custom property fallbacks to `currentColor`.
When you use icons from two different providers like for example: https://lucide.dev/, the fill is set to the current color of the text,

You cannot globally set the `--uui-icon-color` globally to display the new icon properly, without affecting icons from the essential set.

### Steps to reproduce

You just have to implement the uui-icon element with a custom icon from https://lucide.dev/

### Expected result / actual result

This is what we see:
![image](https://github.com/umbraco/Umbraco.UI/assets/53556473/d27e2690-5d3b-48b7-95ab-9ce017e438e7)

**Comment by AyushK-101** [comment]
@UnicornSez I would like to work on this

**Comment by nielslyngsoe** [comment]
Hi @UnicornSez this is fixed, as we now set the color on the icons. and then the SVG should implement 'currentColor' as their color. So you may need to adapt your icons. But even if it a larger package you can find and replace.. lets say stroke="#000" with stroke="currentColor"  or fill="#000" with fill="currentColor".
