### ISSUE TITLE
uui-button: primary buttons and focus issues

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco.UI#641]
Have a look here at the different button looks.
https://uui.umbraco.com/?path=/docs/uui-button--docs

When look is "primary" it is very difficult to see the button has focus, but when hover the button, it's a bit more clear the button has focus.

_Originally posted by @bjarnef in https://github.com/umbraco/Umbraco-CMS/issues/15078#issuecomment-1790903168_

**Comment by julczka** [comment]
Hey, 
I fixed this one soem time ago, so I will close this issue. It works in the same way for different color variants for primary look 
![image](https://github.com/user-attachments/assets/e82617b9-7e93-48a2-8c06-a96a07dc3ac8)
