### ISSUE TITLE
uui-combobox more padding for options

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco.UI#666]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

v1.5.0 @umbraco-ui/uui-combobox

### Bug summary

When navigating the combo box with the keyboard the "current" indicator could benefit from some more padding. Currently it looks like this in the Umbraco backoffice.

![image](https://github.com/umbraco/Umbraco.UI/assets/1782524/8b07a260-4649-40d0-aec6-7b8f678ce438)
,

### Steps to reproduce

Try the combo box here: https://uui.umbraco.com/?path=/docs/uui-form--docs

**Comment by iOvergaard** [comment]
Fixed with #670
