### ISSUE TITLE
UUI-Combobox does not display properly in Safari

### ISSUE THREAD

**Issue by julczka** [umbraco/Umbraco.UI#748]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

1.6.0

### Bug summary

When opened in Safari, the combobox is not displayed properly. The list of options is not visible. This also happens in current release - 1.7.0 (or at least in a release that [uui.umbraco.com/?](uui.umbraco.com/?) points to)

### Specifics

![image](https://github.com/umbraco/Umbraco.UI/assets/56249914/70fe5acc-2784-4caf-96cf-c82cbb8f803c)

### Steps to reproduce

Go to storybook in Safari, open compobox story, try to select some options. Godspeed :smile

### Expected result / actual result

It is possible to see and select the options from combobox in Safari.

**Comment by nielslyngsoe** [comment]
Hi @julczka 

Well spotted, feel free to make a PR for this.

**Comment by mclausen** [comment]
Howdy Team,

I would appreciate it if we could prioritize this task. As one of many Safari users, I find it frustrating to have to switch browsers just to interact efficiently with our products. The UUI-Combobox is a core component used across multiple products, and I believe the priority should reflect its importance.
