### ISSUE TITLE
`:focus-visible` state hardly visible on uui-button element with `color="primary"`

### ISSUE THREAD

**Issue by julczka** [umbraco/Umbraco.UI#749]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

1.6.0

### Bug summary

Default user agent black outline applied when element has `:focus-visible` css pseudoclass attached is hardly noticable whwen `color` attribute is set to `primary` - see attached picture. On it the Navy blue button is surrounded with black outline.

### Specifics

![image](https://github.com/umbraco/Umbraco.UI/assets/56249914/65d5526d-381a-472f-b8ce-d944efa4dec2)

### Steps to reproduce

Tab yourself to a uui-button with primary color, see if you can notice an outline easily. 

### Expected result / actual result

You can see when uui-button is in focus

**Comment by bjarnef** [comment]
I think this is redundant of this issue https://github.com/umbraco/Umbraco.UI/issues/641 🙂
