### ISSUE TITLE
uui-ref-list: Doc Code Snippet does not match up with what is previewed/shown

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco.UI#79]
The code snippet does not match what is shown/displayed as I can not see any `published` tag in the preview above the code sample.
It would be good if the code sample below matched what I see in the preview.

![image](https://user-images.githubusercontent.com/1389894/146900294-033e5b4b-5ea0-4e77-a66b-bdacc5685276.png)

**Comment by JesmoDev** [comment]
this has now been fixed on: [feature/fix-issues](https://github.com/umbraco/Umbraco.UI/tree/feature/fix-issues)
