### ISSUE TITLE
Focus outline on slider should highlight handle

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.UI#878]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

1.9.0

### Bug summary

When focus on slider component it should focus on the actual handle instead of entire slider component. Escpectially if we later supports multiple handles.

![image](https://github.com/user-attachments/assets/2b839e95-88ad-44da-975f-0388c60116a1)

I noticed that besides `uui-slider` https://uui.umbraco.com/?path=/docs/uui-slider--docs we also have `uui-range-slider` https://uui.umbraco.com/?path=/docs/uui-range-slider--docs which set focus on handles.

![image](https://github.com/user-attachments/assets/5293e88f-b88a-4fe0-a7eb-efab181b5ecc)

### Steps to reproduce

Focus on slider component.

**Comment by nielslyngsoe** [comment]
Hi @bjarnef 

Thanks for noticing. I agree with your point. Feel free to make a PR :-)

**Comment by bjarnef** [comment]
It seems this how it works with native slider input, which may be okay with a single handle, but not consistent with multiple handles.

A few examples with handle focused:
https://shoelace.style/components/range/
https://storybook.avonnicomponents.com/?path=/story/example-range--base
