### ISSUE TITLE
Readonly input-color-picker

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco.UI#898]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

1.9.0

### Bug summary

The input-color-picker is missing a `readonly` mode.

### Steps to reproduce

When the `readonly` attribute is set on the element nothing happens.

### Expected result / actual result

When the input is set to `readonly` it should not be possible to update the value. It should be possible to interact with the input to read the value.

Storybook should have a story to showcase the `readonly` mode.

**Comment by bjarnef** [comment]
This one should be simplify enough to implement, when the following PRs has been reviewed/merged:
`uui-color-area`: https://github.com/umbraco/Umbraco.UI/pull/915
`uui-color-swatch`: https://github.com/umbraco/Umbraco.UI/pull/916
`uui-color-slider`: https://github.com/umbraco/Umbraco.UI/pull/917

and then also `uui-color-swatches` ... `uui-input` used on color picker already supports `readonly`.
