### ISSUE TITLE
Storyboard - "Docs" tab - Code is broken on first render

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco.UI#96]
If you follow this sequence:

- navigate to https://uui.umbraco.com/
- switch to the Docs tab

The code window is broken:
```
[object Object],[object Object],[object Object],...
```

Once you are in the Docs tab, navigating to any other component fixes the problem.
I'm using Chrome Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by nielslyngsoe** [comment]
I can confirm that I experience the same.
