### ISSUE TITLE
Fail to import the bundled package in any Typescript project

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco.UI#97]
I'm trying to import the Umbraco.UI components (bundled @umbraco-ui/uui package) in a basic project setup with Webpack as bundler.

index.ts:
```
import './styles.scss';
import '@umbraco-ui/uui/lib';
```

index.html:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <uui-button label="Basic">Basic</uui-button>
</body>
</html>
```

In all the configurations / webpack versions / etc. I tested, I always get the same errors:

First a series of warning like these ones:
```
WARNING in ./node_modules/@umbraco-ui/uui-avatar-group/lib/index.js 7:33-40
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@umbraco-ui/uui/lib/index.js 3:0-48
 @ ./src/index.ts 2:0-29

WARNING in ./node_modules/@umbraco-ui/uui-avatar/lib/index.js 7:33-40
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@umbraco-ui/uui/lib/index.js 2:0-42
 @ ./src/index.ts 2:0-29

. . .
```
And then several errors like this one (I don't know if they are related to the previous warnings)
```
ERROR in ./node_modules/@umbraco-ui/uui-button/lib/index.js 6:0-65
Module not found: Error: Can't resolve '@umbraco-ui/uui-base/lib/svgs/icon-check' in 'D:\01-Codigo\Lit\pruebas-lit2\node_modules\@umbraco-ui\uui-button\lib'
resolve '@umbraco-ui/uui-base/lib/svgs/icon-check' in 'D:\01-Codigo\Lit\pruebas-lit2\node_modules\@umbraco-ui\uui-button\lib'
  Parsed request is a module
  using description file: D:\01-Codigo\Lit\pruebas-lit2\node_modules\@umbraco-ui\uui-button\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      D:\01-Codigo\Lit\pruebas-lit2\node_modules\@umbraco-ui\uui-button\lib\node_modules doesn't exist or is not a directory
      D:\01-Codigo\Lit\pruebas-lit2\node_modules\@umbraco-ui\uui-button\node_modules doesn't exist or is not a directory
      D:\01-Codigo\Lit\pruebas-lit2\node_modules\@umbraco-ui\node_modules doesn't exist or is not a directory
      D:\01-Codigo\Lit\pruebas-lit2\node_modules\node_modules doesn't exist or is not a directory
```

One of the webpack starters I used is this one: https://github.com/Golosay/webpack-seed  ... but I got exactly the same errors with several other setups.

Is there a way to integrate the UI components in a webpack project? Thanks!

**Comment by JoseMarcenaro** [comment]
More information:
With a different, non-webpack tooling (vite) I get the same errors:
```
 > node_modules/@umbraco-ui/uui-button/lib/index.js:6:22: error: Could not resolve "@umbraco-ui/uui-base/lib/svgs/icon-check" (mark it as external to exclude it from the bundle)
    6 │ import IconCheck from '@umbraco-ui/uui-base/lib/svgs/icon-check';
      ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > node_modules/@umbraco-ui/uui-button/lib/index.js:7:22: error: Could not resolve "@umbraco-ui/uui-base/lib/svgs/icon-wrong" (mark it as external to exclude it from the bundle)
    7 │ import IconWrong from '@umbraco-ui/uui-base/lib/svgs/icon-wrong';
      ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

6:13:01 PM [vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/@umbraco-ui/uui-button/lib/index.js:6:22: error: Could not resolve "@umbraco-ui/uui-base/lib/svgs/icon-check" (mark it as external to exclude it from the bundle)
node_modules/@umbraco-ui/uui-button/lib/index.js:7:22: error: Could not resolve "@umbraco-ui/uui-base/lib/svgs/icon-wrong" (mark it as external to exclude it from the bundle)
```

**Comment by JoseMarcenaro** [comment]
Looking at the code in `uui-button.elements.ts:12`
```
import IconCheck from '@umbraco-ui/uui-base/lib/svgs/icon-check';
import IconWrong from '@umbraco-ui/uui-base/lib/svgs/icon-wrong';
```
both .ts files do exist, so it looks like exporting an SVG with `export default svg`<svg ...` is not fully supported.
In fact, these are **the only two exported SVGs** in the entire library - isn't there a different way of doing it?

**Comment by nielslyngsoe** [comment]
Hi @JoseMarcenaro 

Thanks for trying out our repo, as you noticed it's a bit early for production development.
We have forgotten to export the SVGs correctly, this will be corrected in the next version.

It should be good to use with Web Pack, so when this issue is fixed you can try it out again, thanks :-)

I´ll keep the issue open until we have made a new release. :-)

**Comment by JoseMarcenaro** [comment]
Thanks @nielslyngsoe for your clarification. Sounds good to me! :-)

**Comment by iOvergaard** [comment]
Hi @JoseMarcenaro 

Thanks for testing it out. I just tested the latest release with Webpack and it seems we can now run it using Webpack@5 at least where we fixed the SVG error you ran in to.

I created a Stackblitz here with a working example: https://stackblitz.com/edit/github-qyxa98-15y5ub

There is a minor caveat in that you need to instruct Webpack how to handle es modules inside our library using a specific rule, which we will take a look at a later point in time:

```
// webpack.config.j

rules: [
  {
    test: /\.m?js/,
    resolve: {
      fullySpecified: false,
    },
  }
]
```

I hope everything works out for you 😄

**Comment by JoseMarcenaro** [comment]
Thank you very much @iOvergaard  ! I really appreciate this and will fix my setup according to this. 👍
